// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vsoc_top.h for the primary calling header

#ifndef VERILATED_VSOC_TOP___024ROOT_H_
#define VERILATED_VSOC_TOP___024ROOT_H_  // guard

#include "verilated.h"
class Vsoc_top_ibex_pkg;


class Vsoc_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vsoc_top___024root final : public VerilatedModule {
  public:
    // CELLS
    Vsoc_top_ibex_pkg* __PVT__ibex_pkg;

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        CData/*0:0*/ soc_top__DOT__rst_n_int;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__clk;
        CData/*0:0*/ soc_top__DOT__dma_busy;
        CData/*0:0*/ soc_top__DOT__mac_done;
        CData/*2:0*/ soc_top__DOT__mac_fsm_state;
        CData/*0:0*/ soc_top__DOT__instr_req;
        CData/*0:0*/ soc_top__DOT__cpu_gnt;
        CData/*0:0*/ soc_top__DOT__cpu_rvalid;
        CData/*0:0*/ soc_top__DOT__mac_m_rvalid;
        CData/*0:0*/ soc_top__DOT__dma_m_req;
        CData/*0:0*/ soc_top__DOT__dma_m_gnt;
        CData/*0:0*/ soc_top__DOT__dma_m_rvalid;
        CData/*0:0*/ soc_top__DOT__dma_m_we;
        CData/*0:0*/ soc_top__DOT__apb_psel;
        CData/*0:0*/ soc_top__DOT__apb_penable;
        CData/*0:0*/ soc_top__DOT__apb_pwrite;
        CData/*0:0*/ soc_top__DOT__apb_pready;
        CData/*0:0*/ soc_top__DOT__cpu_rvalid_apb;
        CData/*5:0*/ soc_top__DOT__s_psel;
        CData/*0:0*/ soc_top__DOT__d_start;
        CData/*0:0*/ soc_top__DOT__cpu_rvalid_mem;
        CData/*1:0*/ soc_top__DOT__rst_sync;
        CData/*0:0*/ soc_top__DOT____Vcellinp__u_mem__cpu_req;
        CData/*0:0*/ soc_top__DOT____Vcellinp__u_bridge__obi_req;
        CData/*0:0*/ soc_top__DOT__dma_start;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__double_fault_seen_o;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__core_busy_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__core_clock_gate_i__DOT__en_latch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_is_compressed_id;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_gets_expanded_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_fetch_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_fetch_err_plus2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__illegal_c_insn_id;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__imd_val_we_ex;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__icache_inval;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_first_cycle_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_valid_clear;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__pc_set;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__pc_mux_id;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__exc_pc_mux_id;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__exc_cause;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_load_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_store_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_addr_incr_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ctrl_busy;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__rf_we_lsu;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__rf_we_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__mult_sel_ex;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__div_sel_ex;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_access;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_op;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_op_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__illegal_csr_insn_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_in_ready;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_valid;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_resp_valid;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__lsu_resp_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_req_int;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__en_wb;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__data_req_out;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_save_if;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_save_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_restore_mret_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_restore_dret_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_save_cause;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_mtvec_init;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__debug_mode_entering;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__debug_csr_save;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_instr_ret_wb;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_tbranch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_load;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__perf_store;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__illegal_insn_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_valid_id_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_valid_id_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_new_id_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_new_id_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__fetch_valid_raw;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__fetch_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__illegal_c_insn;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_gets_expanded;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__irq_vec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT____Vcellinp__compressed_decoder_i__id_in_ready_i;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT____Vcellinp__compressed_decoder_i__valid_i;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_d;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_q;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_offset_d;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_offset_q;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_state_d;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_state_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__gets_expanded;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__valid_new_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__valid_req_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__discard_req_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__discard_req_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__rdata_outstanding_n;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__rdata_outstanding_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__branch_discard_n;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__branch_discard_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_valid;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT____VdfgTmp_hfdd8329f__0;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__err_d;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__err_q;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__valid_q;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__entry_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__pop_fifo;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__valid;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__aligned_is_compressed;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__unaligned_is_compressed;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__addr_incr_two;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h92feb91f__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_hd659e18c__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h88c42b44__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h077f4b9b__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h46fac9ec__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_haf22c316__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h91d85a72__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h0d1f386f__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h2b0e8186__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_hc11c213a__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h8784150c__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h18c9f4a7__0;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT____VdfgTmp_h0d767ff5__0;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__ebrk_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__mret_insn_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__dret_insn_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__ecall_insn_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__wfi_insn_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__branch_in_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__branch_set;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__branch_set_raw_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__branch_jump_set_done_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__branch_jump_set_done_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__jump_in_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__jump_set_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__jump_set;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__jump_set_raw;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__instr_executing_spec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_run;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__stall_multdiv;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__stall_branch;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__stall_jump;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__stall_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__multicycle_done;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__rf_wdata_sel;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__rf_we_raw;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__rf_ren_a_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__rf_ren_b_dec;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__alu_operator;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__alu_op_a_mux_sel;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__alu_op_a_mux_sel_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__alu_op_b_mux_sel_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__stall_alu;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__imm_a_mux_sel;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__imm_b_mux_sel;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__imm_b_mux_sel_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__mult_en_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__div_en_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__multdiv_en_dec;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__multdiv_operator;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__multdiv_signed_mode;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__lsu_we;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__lsu_type;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__lsu_sign_ext;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__lsu_req_dec;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__id_fsm_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__id_fsm_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__g_branch_set_flop__DOT__branch_set_raw_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__illegal_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__csr_illegal;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__rf_we;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__csr_op;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__opcode;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__decoder_i__DOT__opcode_alu;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_cs;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ctrl_fsm_ns;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__nmi_mode_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__nmi_mode_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__debug_mode_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__debug_mode_d;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__debug_cause_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__load_err_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__store_err_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__exc_req_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__exc_req_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__illegal_insn_q;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__illegal_insn_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__instr_fetch_err_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__illegal_insn_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ecall_insn_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ebrk_insn_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__store_err_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__load_err_prio;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__halt_if;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__retain_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__flush_id;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__special_req;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__do_single_step_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__do_single_step_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__enter_debug_mode_prio_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__enter_debug_mode_prio_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ebreak_into_debug;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ecall_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__mret_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__dret_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__wfi_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__ebrk_insn;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__controller_i__DOT__instr_fetch_err;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__multdiv_sel;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__adder_op_a_shift1;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__adder_op_a_shift2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__adder_op_a_shift3;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__adder_op_b_negate;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__cmp_signed;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__cmp_result;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_left;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__unused_shift_result_ext;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__sign_a;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__sign_b;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__mult_valid;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_sign_a;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_sign_b;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__is_greater_equal;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_valid;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_counter_q;
        CData/*4:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_counter_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__mult_hold;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_hold;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_by_zero_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_by_zero_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__mult_en_internal;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__div_en_internal;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__md_state_q;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__md_state_d;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__gen_mult_fast__DOT__mult_state_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__gen_mult_fast__DOT__mult_state_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__addr_update;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__ctrl_update;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__rdata_update;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__rdata_offset_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_type_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_sign_ext_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_we_q;
        CData/*3:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_be;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__split_misaligned_access;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__handle_misaligned_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__handle_misaligned_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__pmp_err_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__pmp_err_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__lsu_err_q;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__lsu_err_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_or_pmp_err;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__ls_fsm_cs;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__ls_fsm_ns;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__fcov_mis_2_en_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__fcov_mis_2_en_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__fcov_mis_rvalid_2;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__fcov_mis_bus_err_1_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__fcov_mis_bus_err_1_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__priv_lvl_q;
        CData/*1:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__priv_lvl_d;
        CData/*5:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mstatus_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mstatus_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mie_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mscratch_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mepc_en;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcause_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcause_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mtval_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mtvec_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__dcsr_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__depc_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__dscratch0_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__dscratch1_en;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mstack_en;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcountinhibit_d;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcountinhibit_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcountinhibit_we;
        CData/*7:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__cpuctrlsts_part_d;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__cpuctrlsts_part_we;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__csr_we_int;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__csr_wr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__dbg_csr;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__illegal_csr;
        CData/*5:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mstatus_csr__DOT__rdata_q;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mcause_csr__DOT__rdata_q;
        CData/*2:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mstack_csr__DOT__rdata_q;
        CData/*6:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mstack_cause_csr__DOT__rdata_q;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcycle_counter_i__DOT__we;
        CData/*0:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__minstret_counter_i__DOT__we;
        CData/*7:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_cpuctrlsts_part_csr__DOT__rdata_q;
        CData/*3:0*/ soc_top__DOT__u_mem__DOT__arb_be;
        CData/*0:0*/ soc_top__DOT__u_mem__DOT____Vcellinp__u_ram__sram_cen;
        CData/*1:0*/ soc_top__DOT__u_bridge__DOT__state;
        CData/*0:0*/ soc_top__DOT__u_dma_regs__DOT__abort_o;
        CData/*0:0*/ soc_top__DOT__u_dma_regs__DOT__err_i;
        CData/*0:0*/ soc_top__DOT__u_dma_regs__DOT__irq_ack_o;
        CData/*0:0*/ soc_top__DOT__u_dma_core__DOT__done_o;
        CData/*0:0*/ soc_top__DOT__u_dma_core__DOT__err_o;
        CData/*2:0*/ soc_top__DOT__u_dma_core__DOT__state;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__start;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__reg_m;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__reg_k;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__reg_n;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__load_wgt;
        CData/*3:0*/ soc_top__DOT__u_mac__DOT__state;
        CData/*3:0*/ soc_top__DOT__u_mac__DOT__next_state;
        CData/*1:0*/ soc_top__DOT__u_mac__DOT__wgt_cnt;
        CData/*1:0*/ soc_top__DOT__u_mac__DOT__res_cnt;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__row_cnt;
        CData/*3:0*/ soc_top__DOT__u_mac__DOT__feed_cnt;
        CData/*3:0*/ soc_top__DOT__u_mac__DOT__drain_cnt;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__wgt_done_r;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__res_done_r;
    };
    struct {
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__m_req_c;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__m_we_c;
        CData/*0:0*/ soc_top__DOT__u_mac__DOT__u_regs__DOT__sticky_done;
        CData/*3:0*/ soc_top__DOT__u_mac__DOT__u_regs__DOT__pe_addr_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__a_out;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__w_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__a_reg;
        CData/*7:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__w_reg;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__4__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__4__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__4__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__5__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__5__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__6__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__6__sp_offset;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__7__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__7__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__8__Vfuncout;
    };
    struct {
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__8__instr_rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__8__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__9__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__9__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__9__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__9__tmp;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__10__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__10__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__10__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__11__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__11__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__12__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__12__sp_offset;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__13__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__13__rlist;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__18__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__18__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__18__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__19__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__19__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__20__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__20__sp_offset;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__21__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__21__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__22__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__22__instr_rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__22__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__23__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__23__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__23__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_word__23__tmp;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__24__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__24__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__24__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__25__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__25__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__26__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__26__sp_offset;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__27__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__27__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__28__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__28__instr_rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_init__28__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__29__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__30__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__30__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__rlist;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__sp_offset;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__32__Vfuncout;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_rlist_top_reg__32__rlist;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__34__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__34__rlist;
        CData/*1:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj__34__spimm;
        CData/*6:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__35__Vfuncout;
        CData/*3:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_stack_adj_base__35__rlist;
        CData/*2:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__36__rs;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__36__dst;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__37__dst;
        CData/*2:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__38__rs;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__38__dst;
    };
    struct {
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__39__dst;
        CData/*2:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__40__rs;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__40__src;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__41__src;
        CData/*2:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__42__rs;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__42__src;
        CData/*4:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__43__src;
        CData/*1:0*/ __Vdly__soc_top__DOT__u_bridge__DOT__state;
        CData/*2:0*/ __Vdly__soc_top__DOT__u_dma_core__DOT__state;
        CData/*4:0*/ __Vdlyvlsb__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v0;
        CData/*7:0*/ __Vdlyvval__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v0;
        CData/*4:0*/ __Vdlyvlsb__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v1;
        CData/*7:0*/ __Vdlyvval__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v1;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v1;
        CData/*4:0*/ __Vdlyvlsb__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v2;
        CData/*7:0*/ __Vdlyvval__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v2;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v2;
        CData/*4:0*/ __Vdlyvlsb__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v3;
        CData/*7:0*/ __Vdlyvval__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v3;
        CData/*0:0*/ __Vdlyvset__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v3;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__rst_n_int__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__soc_top__DOT__u_core__DOT__clk__0;
        CData/*0:0*/ __VactContinue;
        SData/*15:0*/ soc_top__DOT__d_len;
        SData/*15:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_rdata_c_id;
        SData/*15:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_expanded_id;
        SData/*15:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__gen_mult_fast__DOT__mult_op_a;
        SData/*15:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__gen_mult_fast__DOT__mult_op_b;
        SData/*15:0*/ soc_top__DOT__u_dma_core__DOT__bytes_left;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*15:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__DOT__mul_reg;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__imm;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__imm_signed;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__imm;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__imm_signed;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__neg_offset;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__neg_offset_signed;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__imm;
        SData/*11:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__imm_signed;
        SData/*10:0*/ __Vdlyvdim0__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v0;
        SData/*10:0*/ __Vdlyvdim0__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v1;
        SData/*10:0*/ __Vdlyvdim0__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v2;
        SData/*10:0*/ __Vdlyvdim0__soc_top__DOT__u_mem__DOT__u_ram__DOT__mem__v3;
        IData/*31:0*/ soc_top__DOT__instr_addr;
        IData/*31:0*/ soc_top__DOT__instr_rdata;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__cpu_rdata;
        IData/*31:0*/ soc_top__DOT__dma_m_addr;
        IData/*31:0*/ soc_top__DOT__dma_m_wdata;
        IData/*31:0*/ soc_top__DOT__apb_paddr;
        IData/*31:0*/ soc_top__DOT__apb_pwdata;
        IData/*31:0*/ soc_top__DOT__apb_bus_data;
        IData/*31:0*/ soc_top__DOT__cpu_rdata_apb;
        IData/*31:0*/ soc_top__DOT__s1_prdata;
        IData/*31:0*/ soc_top__DOT__d_src;
        IData/*31:0*/ soc_top__DOT__d_dst;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__rf_wdata_wb;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__rf_rdata_a;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__rf_rdata_b;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__instr_rdata_id;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__pc_id;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__rf_wdata_id;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__alu_operand_b_ex;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__result_ex;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_mtval;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__prefetch_addr;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__fetch_rdata;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__instr_decompressed;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__exc_pc;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__stored_addr_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__stored_addr_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fetch_addr_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fetch_addr_q;
        VlWide<3>/*95:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__rdata_d;
        VlWide<3>/*95:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__rdata;
        IData/*30:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__instr_addr_d;
        IData/*30:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__prefetch_buffer_i__DOT__fifo_i__DOT__instr_addr_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__imm_b;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__alu_operand_a;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_result;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__operand_a_rev;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_operand;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_result;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_result_rev;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__bwlogic_result;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_numerator_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_quotient_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_denominator_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_numerator_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_quotient_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__next_remainder;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__addr_last_q;
        IData/*23:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_wdata;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__load_store_unit_i__DOT__data_rdata_ext;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__exception_pc;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mepc_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mtval_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__dcsr_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__depc_d;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mhpmcounter_we;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mhpmcounterh_we;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mhpmcounter_incr;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__csr_wdata_int;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__csr_rdata_int;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mepc_csr__DOT__rdata_q;
        IData/*17:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mie_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mscratch_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mtval_csr__DOT__rdata_q;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mtvec_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_dcsr_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_depc_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_dscratch0_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_dscratch1_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__u_mstack_epc_csr__DOT__rdata_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__we_a_dec;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__1__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__2__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__3__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__4__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__5__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__6__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__7__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__8__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__9__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__10__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__11__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__12__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__13__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__14__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__15__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__16__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__17__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__18__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__19__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__20__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__21__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__22__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__23__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__24__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__25__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__26__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__27__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__28__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__29__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__30__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__g_rf_flops__BRA__31__KET____DOT__rf_reg_q;
        IData/*31:0*/ soc_top__DOT__u_mem__DOT__arb_addr;
        IData/*31:0*/ soc_top__DOT__u_mem__DOT__arb_wdata;
        IData/*31:0*/ soc_top__DOT__u_mem__DOT__ram_dout;
        IData/*31:0*/ soc_top__DOT__u_dma_core__DOT__curr_src;
        IData/*31:0*/ soc_top__DOT__u_dma_core__DOT__curr_dst;
        IData/*31:0*/ soc_top__DOT__u_dma_core__DOT__data_buffer;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__wgt_addr;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__act_addr;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__res_addr;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__m_addr_c;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__m_wdata_c;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__0__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__1__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__2__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__0__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__1__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__2__KET____DOT__inst_pe__acc_out;
    };
    struct {
        IData/*31:0*/ soc_top__DOT__u_mac__DOT__u_array__DOT____Vcellout__gen_rows__BRA__3__KET____DOT__gen_cols__BRA__3__KET____DOT__inst_pe__acc_out;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__3__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__6__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__6__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__12__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__12__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__17__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__20__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__20__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__26__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_pop_load_reg__26__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__29__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__29__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_push_store_reg__31__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_sp_addi__33__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__36__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__37__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__37__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mvsa01__38__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__39__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__39__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__40__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__41__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__41__instr;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mva01s__42__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__43__Vfuncout;
        IData/*31:0*/ __Vfunc_soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__compressed_decoder_i__DOT__cm_mv_reg__43__instr;
        IData/*31:0*/ __Vdly__soc_top__DOT__u_dma_core__DOT__curr_src;
        IData/*31:0*/ __VactIterCount;
        QData/*32:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__multdiv_alu_operand_b;
        QData/*32:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__multdiv_alu_operand_a;
        QData/*33:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_adder_result_ext;
        QData/*32:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_result_ext_signed;
        QData/*32:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__shift_result_ext;
        QData/*33:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__accum;
        QData/*33:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__mac_res_d;
        QData/*33:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__op_remainder_d;
        QData/*32:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__gen_multdiv_fast__DOT__multdiv_i__DOT__next_quotient;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcycle_counter_i__DOT__counter_load;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcycle_counter_i__DOT__counter_d;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mcycle_counter_i__DOT__counter_q;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__minstret_counter_i__DOT__counter_load;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__minstret_counter_i__DOT__counter_d;
        QData/*63:0*/ soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__minstret_counter_i__DOT__counter_q;
        VlUnpacked<IData/*21:0*/, 2> soc_top__DOT__u_core__DOT__ic_tag_rdata;
        VlUnpacked<QData/*63:0*/, 2> soc_top__DOT__u_core__DOT__ic_data_rdata;
        VlUnpacked<QData/*33:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__imd_val_d_ex;
        VlUnpacked<QData/*33:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__imd_val_q_ex;
        VlUnpacked<QData/*33:0*/, 4> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_pmp_addr;
        VlUnpacked<CData/*5:0*/, 4> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__csr_pmp_cfg;
        VlUnpacked<CData/*0:0*/, 3> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__pmp_req_err;
        VlUnpacked<QData/*33:0*/, 4> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__g_no_pmp__DOT__unused_csr_pmp_addr;
        VlUnpacked<CData/*5:0*/, 4> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__g_no_pmp__DOT__unused_csr_pmp_cfg;
        VlUnpacked<IData/*21:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__unused_tag_ram_input;
        VlUnpacked<QData/*63:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__if_stage_i__DOT__gen_prefetch_buffer__DOT__unused_data_ram_input;
        VlUnpacked<QData/*33:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__id_stage_i__DOT__imd_val_q;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_imd_val_q;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_imd_val_d;
        VlUnpacked<QData/*33:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__multdiv_imd_val_d;
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__ex_block_i__DOT__alu_i__DOT__g_no_alu_rvb__DOT__unused_imd_val_q;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 2> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__wb_stage_i__DOT__rf_wdata_wb_mux;
        VlUnpacked<IData/*31:0*/, 16> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__pmp_addr_rdata;
        VlUnpacked<CData/*7:0*/, 16> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__pmp_cfg_rdata;
        VlUnpacked<QData/*63:0*/, 32> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mhpmcounter;
        VlUnpacked<IData/*31:0*/, 32> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__mhpmevent;
        VlUnpacked<IData/*31:0*/, 32> soc_top__DOT__u_core__DOT__gen_regfile_ff__DOT__register_file_i__DOT__rf_reg;
        VlUnpacked<IData/*31:0*/, 1024> soc_top__DOT__u_mem__DOT__u_rom__DOT__rom;
        VlUnpacked<IData/*31:0*/, 2048> soc_top__DOT__u_mem__DOT__u_ram__DOT__mem;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 4> soc_top__DOT__u_mac__DOT__wgt_buf;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 4> soc_top__DOT__u_mac__DOT__weight_in;
        VlUnpacked<CData/*7:0*/, 4> soc_top__DOT__u_mac__DOT__act_buf;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__res_buf;
        VlUnpacked<CData/*7:0*/, 4> soc_top__DOT__u_mac__DOT__row_in;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__col_in;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__col_out;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__result_hold;
        VlUnpacked<CData/*7:0*/, 4> soc_top__DOT__u_mac__DOT__u_array__DOT__row_in;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 4>, 4> soc_top__DOT__u_mac__DOT__u_array__DOT__weight_in;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__u_array__DOT__col_in;
        VlUnpacked<IData/*31:0*/, 4> soc_top__DOT__u_mac__DOT__u_array__DOT__col_out;
        VlUnpacked<VlUnpacked<CData/*7:0*/, 5>, 4> soc_top__DOT__u_mac__DOT__u_array__DOT__h_wire;
        VlUnpacked<VlUnpacked<IData/*31:0*/, 4>, 5> soc_top__DOT__u_mac__DOT__u_array__DOT__v_wire;
        VlUnpacked<CData/*0:0*/, 9> __Vm_traceActivity;
    };
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<6> __VactTriggered;
    VlTriggerVec<6> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vsoc_top__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr VlUnpacked<QData/*33:0*/, 16> soc_top__DOT__u_core__DOT__PMPRstAddr = {{
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL
    }};
    static constexpr VlUnpacked<QData/*33:0*/, 16> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__PMPRstAddr = {{
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL
    }};
    static constexpr VlUnpacked<QData/*33:0*/, 16> soc_top__DOT__u_core__DOT__u_ibex_core__DOT__cs_registers_i__DOT__PMPRstAddr = {{
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL,
        0x0000000000000000ULL, 0x0000000000000000ULL
    }};

    // CONSTRUCTORS
    Vsoc_top___024root(Vsoc_top__Syms* symsp, const char* v__name);
    ~Vsoc_top___024root();
    VL_UNCOPYABLE(Vsoc_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
